declare global {
  interface ShanHaiWindowState extends ShanHaiDataRecord {
    open: boolean;
    left: number;
    top: number;
    z: number;
    minimized: boolean;
    dockSide: string | null;
  }

  interface ShanHaiUiState extends ShanHaiDataRecord {
    speed: number;
    lastLoopTime: number;
    saveState: string;
    selectedLocationId: string;
    selectedTab: string;
    windows: Record<string, ShanHaiWindowState>;
    windowZCounter: number;
  }

  interface ShanHaiRuntimeState extends ShanHaiDataRecord {
    game: ShanHaiGameState | null;
    initialized: boolean;
    loopHandle: number;
    autoSaveHandle: number;
    mapTexture: ShanHaiMapTexture | null;
    mapViewport: ShanHaiMapViewport | null;
    mapInteraction: ShanHaiMapInteractionState | null;
    mapIgnoreClick: boolean;
    battleFlash: number;
    activeWindowDrag: ShanHaiWindowDragState | null;
    windowEventsBound: boolean;
    windowLayoutLoaded: boolean;
    interactionsBound: boolean;
  }

  interface ShanHaiRuntimeUtils {
    randomInt: (min: number, max: number) => number;
    randomFloat: (min: number, max: number) => number;
    sample: <T>(array: T[]) => T;
    clamp: (value: number, min: number, max: number) => number;
    round: (value: number, digits?: number) => number;
    formatNumber: (value: number | string) => string;
    uid: (prefix: string) => string;
    buildMapTexture: () => ShanHaiMapTexture;
    deepClone: <T>(value: T) => T;
    ensureArray: <T>(value: T[] | null | undefined | unknown) => T[];
  }

  interface ShanHaiPlayerFactionBranchDef extends ShanHaiDataRecord {
    label: string;
    desc: string;
    baseCost: number;
  }

  interface ShanHaiSocialInternals extends ShanHaiDataRecord {
    createTask: <T extends ShanHaiTaskState>(ownerType: string, kind: string, payload?: Omit<T, "id" | "kind" | "ownerType">) => T;
    createFactionName: () => string;
    createSectName: () => string;
    createTerritoryEntry: (locationId: string) => ShanHaiTerritoryState;
    getFactionLiquidFunds: () => number;
    getPlayerFactionTotalCrew: (playerFaction?: ShanHaiPlayerFactionState | null) => number;
    getTerritoryControllerName: (territory: ShanHaiTerritoryState) => string;
    spendFactionLiquidFunds: (amount: number) => boolean;
  }

  interface ShanHaiIndustryInternals extends ShanHaiDataRecord {
    DEED_ITEM_BY_KIND: Record<string, string>;
    GOVERNMENT_CONTRACTS: Record<string, ShanHaiGovernmentContractData>;
    INDUSTRY_UPGRADE_BASE_COST: Record<string, number>;
    SECT_UNLOCK_BY_KIND?: Record<string, string>;
    getAssets: (kind: ShanHaiAssetKind) => ShanHaiAssetState[];
    getAsset: (kind: ShanHaiAssetKind, assetId: string) => ShanHaiAssetState | undefined;
    getManagedAssetByNpcId: (npcId: string) => (ShanHaiAssetState & { kind?: ShanHaiAssetKind }) | null;
    getAssetOperatorBonus: (asset: ShanHaiAssetState | null | undefined) => number;
    getIndustrySupportBonus: (kind: ShanHaiAssetKind, locationId: string) => Record<string, number>;
    applyIndustryNetworkGrowth: (...args: unknown[]) => unknown;
    getGovernmentStandingNeed: (kind: ShanHaiAssetKind, locationId?: string) => number;
    hasIndustryAccess: (kind: ShanHaiAssetKind, property?: ShanHaiPropertyDef | null) => boolean;
    spendIndustryFunds: (amount: number) => boolean;
  }

  interface ShanHaiDomRefs {
    dayLabel: HTMLElement;
    timeLabel: HTMLElement;
    reputationLabel: HTMLElement;
    saveStateLabel: HTMLElement;
    heroFocusLabel: HTMLElement;
    heroRouteLabel: HTMLElement;
    currentLocationLabel: HTMLElement;
    modeLabel: HTMLElement;
    actionLabel: HTMLElement;
    locationDetail: HTMLElement;
    playerPanel: HTMLElement;
    dockPanel: HTMLElement;
    commandDetail: HTMLElement;
    inventoryPanel: HTMLElement;
    industryPanel: HTMLElement;
    marketPanel: HTMLElement;
    auctionPanel: HTMLElement;
    combatPanel: HTMLElement;
    npcPanel: HTMLElement;
    sectPanel: HTMLElement;
    worldPanel: HTMLElement;
    logList: HTMLElement;
    profileDetail: HTMLElement;
    mapCanvasShell: HTMLElement;
    mapCanvas: HTMLCanvasElement;
    mapZoomLabel: HTMLElement;
    saveButton: HTMLElement;
    loadButton: HTMLElement;
    newGameButton: HTMLElement;
    openJournalButton: HTMLElement;
    openMapButton: HTMLElement;
    openCommandButton: HTMLElement;
    openProfileButton: HTMLElement;
    closeJournalButton: HTMLElement;
    closeMapButton: HTMLElement;
    closeCommandButton: HTMLElement;
    closeProfileButton: HTMLElement;
    journalWindow: HTMLElement;
    mapWindow: HTMLElement;
    commandWindow: HTMLElement;
    profileWindow: HTMLElement;
    speedSwitch: HTMLElement;
    focusPlayerButton: HTMLElement;
    clearLogButton: HTMLElement;
    tabStrip: HTMLElement;
    toastStack: HTMLElement;
  }

  interface ShanHaiApp extends ShanHaiDataRecord {
    config: ShanHaiRuntimeConfig;
    dom: ShanHaiDomRefs;
    industryInternals: ShanHaiIndustryInternals;
    runtime: ShanHaiRuntimeState;
    socialInternals: ShanHaiSocialInternals;
    state: ShanHaiUiState;
    tables: ShanHaiRuntimeTables;
    utils: ShanHaiRuntimeUtils;
    PLAYER_FACTION_BRANCHES: Record<string, ShanHaiPlayerFactionBranchDef>;
    getGame: () => ShanHaiGameState;
    setGame: (nextGame: ShanHaiGameState) => ShanHaiGameState;
    initialize: () => void;
    render: () => void;
    loop: (timestamp: number) => void;
    startLoop: () => void;
    startAutoSave: () => void;
    bindDom: () => void;
    bindEvents: () => void;
    bindWindowEvents: () => void;
    createRelationState: () => ShanHaiRelationState;
    deriveLifeStage: (age: number) => string;
    createInitialSect: (name?: string) => ShanHaiSectState;
    createInitialPlayerFaction: (name?: string) => ShanHaiPlayerFactionState;
    createInitialTerritories: () => Record<string, ShanHaiTerritoryState>;
    createInitialPlayer: () => ShanHaiPlayerState;
    createLootBundle: (amount: number, options?: ShanHaiDataRecord) => ShanHaiInventoryEntry[];
    createNPC: (index: number) => ShanHaiNpcState;
    createMarketListings: (location: ShanHaiLocationData) => ShanHaiMarketListing[];
    createInitialMarket: () => Record<string, ShanHaiMarketListing[]>;
    createAuctionListings: (amount: number) => ShanHaiAuctionListing[];
    createInitialWorld: () => ShanHaiWorldState;
    createInitialCombat: () => ShanHaiCombatState;
    createGameState: () => ShanHaiGameState;
    hydrateGameState: (raw?: Partial<ShanHaiGameState>) => ShanHaiGameState;
    getRankData: (rankIndex: number) => ShanHaiRankData;
    getCurrentLocation: () => ShanHaiLocationData;
    getSelectedLocation: () => ShanHaiLocationData;
    getItem: (itemId: string) => ShanHaiItemData | undefined | null;
    getNpc: (npcId: string) => ShanHaiNpcState | null;
    getRealm: (realmId: string) => ShanHaiRealmTemplate | null;
    getMonsterTemplate: (monsterId: string) => ShanHaiMonsterTemplate | null;
    getFaction: (factionId: string | null) => ShanHaiFactionData | null;
    getPropertyDef: (propertyId: string) => ShanHaiPropertyDef | null;
    getCrop: (cropId: string) => ShanHaiCropData | null;
    getRecipe: (recipeId: string) => ShanHaiCraftRecipe | null;
    findInventoryEntry: (itemId: string) => ShanHaiInventoryEntry | null;
    ensurePlayerRelation: (npcId: string) => ShanHaiRelationState;
    addItemToInventory: (itemId: string, quantity?: number) => void;
    removeItemFromInventory: (itemId: string, quantity?: number) => boolean;
    adjustResource: (key: string, amount: number, maxKey?: string) => void;
    appendLog: (text: string, type?: ShanHaiLogType) => void;
    updateDerivedStats: () => void;
    getPlayerPower: () => number;
    getPlayerInsight: () => number;
    getPlayerCharisma: () => number;
    setMode: (modeId: ShanHaiModeId) => void;
    getNextBreakthroughNeed: () => number;
    checkRankGrowth: () => void;
    attemptBreakthrough: () => boolean;
    consumeItem: (itemId: string) => boolean | void;
    saveGame: (announce?: boolean) => void;
    loadGame: () => void;
    resetGame: () => void;
    revivePlayer: () => void;
    stashManualToSect: (itemId?: string) => void;
    sellItem: (itemId: string) => void;
    forceAction: (actionKey: string) => void;
    applyPassiveAction: (actionKey: string) => void;
    getCombat: () => ShanHaiCombatState;
    getAffix: (affixId: string) => ShanHaiMonsterAffix | null;
    startEncounter: (source?: string) => ShanHaiEnemyState | null;
    challengeRealm: (realmId: string) => void;
    processBattleRound: (action?: string) => void;
    autoCombatTick: () => void;
    maybeStartEncounter: (actionKey?: string) => boolean;
    travelTo: (locationId: string) => void;
    travelAndAct: (locationId: string, action: string) => void;
    chooseAutoAction: () => string | null;
    performAction: (actionKey: string) => void;
    tickWorld: () => void;
    gameStep: () => void;
    maybeActivateRealm: () => void;
    refreshMarketIfNeeded: () => void;
    runNpcAI: () => void;
    resolveAuctionTurn: () => void;
    resolveAuctionVisit: () => void;
    resolvePassiveTrade: () => void;
    startTradeRun: (destinationId: string) => boolean;
    getActiveTradeRun: () => ShanHaiTradeRunState | null;
    advanceTradeRun: () => string;
    maybeStartBestTradeRun: () => boolean;
    findRoute: (fromId: string, toId: string) => string[] | null;
    currentLocationCanReach: (locationId: string) => boolean;
    getTradeRouteOptions: (locationId?: string) => ShanHaiTradeRouteOption[];
    isTradeHub: (location?: ShanHaiLocationData) => boolean;
    adjustFactionStanding: (factionId: string | null, delta: number) => void;
    adjustRegionStanding: (locationId: string, delta: number) => void;
    adjustRelation: (npcId: string, delta?: Partial<ShanHaiRelationState>) => ShanHaiRelationState;
    getCurrentAffiliation: () => ShanHaiFactionData | null;
    getFactionTypeLabel: (type: string) => string;
    getGovernmentOfficeName: (locationId?: string) => string;
    getLocationOfficialFactions: (locationId?: string) => ShanHaiFactionData[];
    getPlayerFaction: () => ShanHaiPlayerFactionState | null;
    getPlayerFactionTotalCrew: (playerFaction?: ShanHaiPlayerFactionState | null) => number;
    getRegionStanding: (locationId?: string) => number;
    getRelation: (npcId: string) => ShanHaiRelationState;
    getTerritoryState: (locationId: string) => ShanHaiTerritoryState;
    isOfficialFaction: (factionOrId: string | ShanHaiFactionData | null) => boolean;
    isTradeHubLocation: (locationId: string) => boolean;
    canCompleteAffiliationTask: (taskId: string) => boolean;
    canJoinFaction: (factionId: string) => boolean;
    completeAffiliationTask: (taskId: string) => void;
    explainAffiliationTask: (taskId: string) => string;
    explainFactionJoin: (factionId: string) => string;
    getAffiliationTaskIssues: (taskId: string) => string[];
    getAffiliationTasks: () => ShanHaiTaskState[];
    getFactionJoinIssues: (factionId: string) => string[];
    joinFaction: (factionId: string) => void;
    refreshAffiliationTasks: (force?: boolean) => ShanHaiTaskState[];
    canCompletePlayerFactionMission: (missionId: string) => boolean;
    canCreatePlayerFaction: () => boolean;
    canRecruitFactionMember: (npcId: string) => boolean;
    completePlayerFactionMission: (missionId: string) => void;
    createPlayerFaction: () => void;
    explainCreatePlayerFaction: () => string;
    explainPlayerFactionMission: (missionId: string) => string;
    explainRecruitFactionMember: (npcId: string) => string;
    getCreatePlayerFactionIssues: () => string[];
    getPlayerFactionMissionIssues: (missionId: string) => string[];
    getPlayerFactionMissions: () => ShanHaiTaskState[];
    getRecruitFactionMemberIssues: (npcId: string) => string[];
    processPlayerFactionTick: () => void;
    recruitFactionMember: (npcId: string) => void;
    refreshPlayerFactionMissions: (force?: boolean) => ShanHaiTaskState[];
    upgradePlayerFactionBranch: (branchKey: string) => void;
    assignTeaching: (npcId: string, manualId?: string) => void;
    becomeMasterBond: (npcId: string) => void;
    becomePartner: (npcId: string) => void;
    canBecomeMaster: (npcId: string) => boolean;
    canBecomePartner: (npcId: string) => boolean;
    canCompleteSectMission: (missionId: string) => boolean;
    canRecruitDisciple: (npcId: string) => boolean;
    completeSectMission: (missionId: string) => void;
    createSect: () => void;
    declareRival: (npcId: string) => void;
    explainMasterBond: (npcId: string) => string;
    explainPartnerBond: (npcId: string) => string;
    explainRecruitDisciple: (npcId: string) => string;
    explainSectMission: (missionId: string) => string;
    getMasterBondIssues: (npcId: string) => string[];
    getPartnerBondIssues: (npcId: string) => string[];
    getRecruitDiscipleIssues: (npcId: string) => string[];
    getSectMissionIssues: (missionId: string) => string[];
    getSectMissions: () => ShanHaiTaskState[];
    processSectTick: () => void;
    recruitDisciple: (npcId: string) => void;
    refreshSectMissions: (force?: boolean) => ShanHaiTaskState[];
    upgradeSectBuilding: (buildingKey: string) => void;
    canLaunchTerritoryCampaign: (locationId: string) => boolean;
    canStabilizeTerritory: (locationId: string) => boolean;
    explainStabilizeTerritory: (locationId: string) => string;
    explainTerritoryCampaign: (locationId: string) => string;
    getPlayerFactionTerritories: () => ShanHaiTerritoryTarget[];
    getPlayerFactionTerritoryTargets: () => ShanHaiTerritoryTarget[];
    getPlayerTerritoryModifier: (locationId: string) => number;
    getTerritoryCampaignIssues: (locationId: string) => string[];
    getTerritoryStabilizeIssues: (locationId: string) => string[];
    launchTerritoryCampaign: (locationId: string) => void;
    stabilizeTerritory: (locationId: string) => void;
    processRelationshipTick: () => void;
    visitNpc: (npcId: string) => void;
    getAssetDelegateCandidates: () => ShanHaiNpcState[];
    getAssetManager: (kind: ShanHaiAssetKind, assetId: string) => ShanHaiNpcState | null;
    getAssetManagerLabel: (asset: ShanHaiAssetState | null | undefined) => string;
    getAssetAutomationLabel: (kind: ShanHaiAssetKind, asset: ShanHaiAssetState | null | undefined) => string;
    getAvailableProperties: () => ShanHaiPropertyDef[];
    getLocalProperties: (kind?: ShanHaiAssetKind) => ShanHaiPropertyDef[];
    getGovernmentContractOffers: () => ShanHaiGovernmentContractOffer[];
    getGovernmentContractIssues: (kind: ShanHaiAssetKind) => string[];
    explainGovernmentContract: (kind: ShanHaiAssetKind) => string;
    canPurchaseGovernmentContract: (kind: ShanHaiAssetKind) => boolean;
    purchaseGovernmentContract: (kind: ShanHaiAssetKind) => void;
    getIndustryOrders: () => ShanHaiIndustryOrderState[];
    refreshIndustryOrders: (force?: boolean) => ShanHaiIndustryOrderState[];
    canFulfillIndustryOrder: (orderId: string) => boolean;
    getIndustryOrderIssues: (orderId: string) => string[];
    explainIndustryOrder: (orderId: string) => string;
    fulfillIndustryOrder: (orderId: string) => void;
    canPurchaseProperty: (propertyId: string) => boolean;
    getPropertyPurchaseIssues: (propertyId: string) => string[];
    explainPropertyPurchase: (propertyId: string) => string;
    purchaseProperty: (propertyId: string) => void;
    getAssignAssetManagerIssues: (kind: ShanHaiAssetKind, assetId: string, npcId: string) => string[];
    explainAssignAssetManager: (kind: ShanHaiAssetKind, assetId: string, npcId: string) => string;
    canAssignAssetManager: (kind: ShanHaiAssetKind, assetId: string, npcId: string) => boolean;
    assignAssetManager: (kind: ShanHaiAssetKind, assetId: string, npcId: string) => void;
    clearAssetManager: (kind: ShanHaiAssetKind, assetId: string) => void;
    getSetAssetPlanIssues: (kind: ShanHaiAssetKind, assetId: string, targetId: string) => string[];
    explainSetAssetPlan: (kind: ShanHaiAssetKind, assetId: string, targetId: string) => string;
    canSetAssetPlan: (kind: ShanHaiAssetKind, assetId: string, targetId: string) => boolean;
    setAssetPlan: (kind: ShanHaiAssetKind, assetId: string, targetId: string) => void;
    getAssetUpgradeCost: (kind: ShanHaiAssetKind, assetId: string) => number;
    getAssetUpgradeIssues: (kind: ShanHaiAssetKind, assetId: string) => string[];
    explainAssetUpgrade: (kind: ShanHaiAssetKind, assetId: string) => string;
    canUpgradeAsset: (kind: ShanHaiAssetKind, assetId: string) => boolean;
    upgradeAsset: (kind: ShanHaiAssetKind, assetId: string) => void;
    plantCrop: (assetId: string, cropId: string) => void;
    harvestCrop: (assetId: string) => void;
    getHarvestIssues: (assetId: string) => string[];
    explainHarvest: (assetId: string) => string;
    canCraftRecipe: (recipeId: string) => boolean;
    getCraftRecipeIssues: (recipeId: string) => string[];
    explainCraftRecipe: (recipeId: string) => string;
    craftRecipe: (recipeId: string) => void;
    restockShop: (assetId: string) => void;
    collectShopIncome: (assetId: string) => void;
    processIndustryTick: () => void;
    buyListing: (listingId: string) => void;
    placeBid: (listingId: string) => void;
    processNpcLifeTick: () => void;
    renderTopBar: () => void;
    renderPlayerPanel: () => void;
    renderWorkbenchControls: () => void;
    renderProfileWindow: () => void;
    renderDockPanel: () => void;
    renderLocationDetail: () => void;
    renderInventoryPanel: () => void;
    renderIndustryPanel: () => void;
    renderMarketPanel: () => void;
    renderAuctionPanel: () => void;
    renderCombatPanel: () => void;
    renderNpcPanel: () => void;
    renderSectPanel: () => void;
    renderWorldPanel: () => void;
    renderLog: () => void;
    renderTabs: () => void;
    renderMap: () => void;
    renderFloatingWindows: () => void;
    renderSpeedButtons: () => void;
    getModeLabel: (modeId: ShanHaiModeId) => string;
    getRoleLabel: (role: string) => string;
    getMarketBiasLabel: (type: string) => string;
    getUnlockLabel: (type: string) => string;
    formatUnlockLabels: (unlocks?: string[]) => string;
    getGuardAttrs: (enabled: boolean, reason?: string) => string;
    showFeedback: (text: string, type?: ShanHaiLogType) => void;
    describeItemEffect: (item: ShanHaiItemData | null | undefined) => string;
    renderMeter: (label: string, value: number, max: number, className?: string) => string;
    ensureWindowState: (windowId: ShanHaiWindowId) => ShanHaiWindowState;
    openWindow: (windowId: ShanHaiWindowId) => void;
    closeWindow: (windowId: ShanHaiWindowId) => void;
    toggleWindow: (windowId: ShanHaiWindowId) => void;
    closeTopWindow: () => void;
    toggleWindowMinimize: (windowId: ShanHaiWindowId) => void;
    toggleWindowDock: (windowId: ShanHaiWindowId) => void;
    bringWindowToFront: (windowId: ShanHaiWindowId) => void;
    startWindowDrag: (windowId: ShanHaiWindowId, event: Event) => void;
    persistWindowLayout: () => void;
    getClosest: (target: EventTarget | null, selector: string) => HTMLElement | null;
    handleBlockedControl: (event: Event) => boolean;
    showLocationOnMap: (locationId: string) => void;
    travelOnly: (locationId: string) => void;
    runQuickAction: (action: string) => boolean;
    onCanvasClick: (event: Event) => void;
    onCanvasPointerDown: (event: Event) => void;
    onCanvasPointerMove: (event: Event) => void;
    stopCanvasPointer: (event: Event) => void;
    onCanvasWheel: (event: Event) => void;
    handleMapWindowClick: (event: Event) => void;
    ensureMapViewport: () => ShanHaiMapViewport;
    clampMapViewport: (viewport: ShanHaiMapViewport) => ShanHaiMapViewport;
    getCanvasPointFromEvent: (event: MouseEvent | PointerEvent | WheelEvent) => ShanHaiPoint | null;
    getMapWorldPointFromEvent: (event: MouseEvent | PointerEvent | WheelEvent) => ShanHaiPoint | null;
    focusMapOnLocation: (locationId: string, options?: ShanHaiMapFocusOptions) => void;
    resetMapViewport: () => void;
    zoomMap: (factor: number, anchorX?: number, anchorY?: number) => void;
    drawMapTexture: (context: CanvasRenderingContext2D) => void;
    drawRoutes: (context: CanvasRenderingContext2D) => void;
    drawLocationNodes: (context: CanvasRenderingContext2D, selected: ShanHaiLocationData, current: ShanHaiLocationData, activeRealmId?: string | null) => void;
    drawPlayerTrail: (context: CanvasRenderingContext2D, current: ShanHaiLocationData) => void;
    handlePlayerPanelClick: (event: Event) => void;
    handleLocationDetailClick: (event: Event) => void;
    handleInventoryClick: (event: Event) => void;
    handleMarketClick: (event: Event) => void;
    handleAuctionClick: (event: Event) => void;
    handleIndustryClick: (event: Event) => void;
    handleCombatClick: (event: Event) => void;
    handleNpcClick: (event: Event) => void;
    handleSectClick: (event: Event) => void;
    handleWorldClick: (event: Event) => void;
    handleDockClick: (event: Event) => void;
  }

  interface Window {
    ShanHai: ShanHaiApp;
  }
}

export {};
