export interface LocationData {
  id: string
  name: string
  x: number
  y: number
  region: string
  danger: number
  marketBias: string
  marketTier: number
  aura: number
  terrain: string
  desc: string
  actions: string[]
  /** 邻居地点ID */
  neighbors: string[]
  resource: string
  realmId: string | null
  tags: string[]
  /** 派系/势力ID */
  factionIds: string[]
}

function withBidirectionalNeighbors(locations: LocationData[]) {
  const neighborMap = new Map(locations.map(location => [location.id, [...location.neighbors]]))
  locations.forEach(location => {
    location.neighbors.forEach(neighborId => {
      const reverse = neighborMap.get(neighborId)
      if (reverse && !reverse.includes(location.id)) reverse.push(location.id)
    })
  })
  return locations.map(location => ({ ...location, neighbors: neighborMap.get(location.id) || [] }))
}

export const LOCATIONS: LocationData[] = withBidirectionalNeighbors([
  { id: "hemingtai", name: "鹤鸣台", x: 980, y: 80, region: "云崖", danger: 4, marketBias: "scroll", marketTier: 3, aura: 49, terrain: "鹤鸣高台", desc: "一座孤零零的石台伸出崖外，常有白鹤落在台边的老松上。散修们在台下摆地摊，卖的多是缺页的旧经。", actions: ["meditate", "train", "quest", "sect"], neighbors: ["hanxi", "starfall", "tianchi"], resource: "鹤羽残简", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "danjing", name: "丹井坪", x: 1225, y: 80, region: "丹岭", danger: 4, marketBias: "pill", marketTier: 3, aura: 52, terrain: "丹井石坪", desc: "坪中央有口古井，井沿摸上去是温的。行院的丹房在这里起了几座炉子，风里总带着一股焦苦的药味。", actions: ["meditate", "breakthrough", "quest", "sect"], neighbors: ["jadegate", "starfall", "yaogu"], resource: "丹井灵汞", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "snowpeak", name: "寒魄峰", x: 725, y: 125, region: "雪原", danger: 4, marketBias: "ice", marketTier: 3, aura: 44, terrain: "雪峰洞府", desc: "山顶的冰一年到头不化，夜里能听见冰层底下有水在走。上山闭关的人不少，下来的没那么多。", actions: ["meditate", "breakthrough", "hunt"], neighbors: ["hanxi", "misty", "qingsong", "shuangqiao"], resource: "寒魄晶", realmId: "ice-cavern", tags: ["cultivation"], factionIds: [] },
  { id: "hanxi", name: "寒溪坞", x: 850, y: 125, region: "寒溪", danger: 3, marketBias: "ice", marketTier: 2, aura: 40, terrain: "冰溪谷地", desc: "一条溪水绕着山谷拐了三道弯，水冷得扎手。谷里散住着几户人家，也有修士在溪边搭了草庐。", actions: ["meditate", "breakthrough", "hunt"], neighbors: ["hemingtai", "shuangqiao", "snowpeak", "tianchi"], resource: "寒溪冰髓", realmId: null, tags: ["cultivation"], factionIds: [] },
  { id: "starfall", name: "星坠谷", x: 1115, y: 135, region: "秘境", danger: 6, marketBias: "scroll", marketTier: 5, aura: 60, terrain: "陨星裂谷", desc: "传说早年有颗星星掉在这里，砸出一道裂谷。谷底的石头黑得发亮，捡一块揣在怀里，半夜会自己发烫。", actions: ["quest", "hunt", "breakthrough"], neighbors: ["danjing", "hemingtai", "jadegate", "redcliff", "tianchi", "yunling"], resource: "陨星残页", realmId: "star-sanctum", tags: ["boss", "endgame"], factionIds: [] },
  { id: "qingsong", name: "青松坳", x: 585, y: 155, region: "山阴", danger: 3, marketBias: "wood", marketTier: 1, aura: 34, terrain: "青松险坳", desc: "坳口全是老松和乱石，只留一条窄道。迷林猎社的人常蹲在道边，上山下山的都得跟他们打个照面。", actions: ["hunt", "quest", "meditate"], neighbors: ["misty", "snowpeak", "songlan", "yuelu"], resource: "坳口青木", realmId: null, tags: ["wild", "cultivation"], factionIds: ["mist-hunt-lodge"] },
  { id: "yaogu", name: "药谷坪", x: 1360, y: 160, region: "药谷", danger: 3, marketBias: "herb", marketTier: 2, aura: 44, terrain: "药雾深坪", desc: "一进坪子就闻到药香。采药客背着竹篓在这儿歇脚，丹房的人隔三岔五下来收货，按斤论价。", actions: ["meditate", "trade", "quest"], neighbors: ["danjing", "jadegate", "longji", "songtao"], resource: "药谷灵苗", realmId: null, tags: ["cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "songtao", name: "松涛驿", x: 1560, y: 200, region: "海岬", danger: 3, marketBias: "scroll", marketTier: 2, aura: 28, terrain: "松涛岬驿", desc: "海岬上的一座旧驿站，松林一刮风就哗哗地响。过路的人大多不爱说自己从哪来，包袱也捂得紧。", actions: ["trade", "quest", "meditate"], neighbors: ["longji", "yaogu"], resource: "潮湿旧卷", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort"] },
  { id: "tianchi", name: "天池坪", x: 945, y: 215, region: "高岭", danger: 4, marketBias: "pill", marketTier: 3, aura: 46, terrain: "天池高坪", desc: "雪水化开，在高处积成一汪池子，池边长着青苔似的水藻。有人在水边一坐就是一夜，天亮时眉毛上结着霜。", actions: ["meditate", "breakthrough", "quest"], neighbors: ["hanxi", "hemingtai", "shuangqiao", "starfall", "yunling"], resource: "天池灵藻", realmId: null, tags: ["cultivation"], factionIds: [] },
  { id: "shuangqiao", name: "霜桥镇", x: 805, y: 220, region: "雪麓", danger: 2, marketBias: "ice", marketTier: 1, aura: 36, terrain: "霜桥古道", desc: "进寒原前最后一个像样的镇子。镇口有座石桥，桥下的泉水冬天也不结冰，终日冒着白气。", actions: ["meditate", "train", "trade"], neighbors: ["hanxi", "snowpeak", "tianchi", "yuelu"], resource: "霜桥泉玉", realmId: null, tags: ["town", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "misty", name: "迷雾林", x: 505, y: 255, region: "林海", danger: 2, marketBias: "wood", marketTier: 1, aura: 34, terrain: "迷雾丛林", desc: "林子里的雾从早到晚不散，三步外就看不清人。常有采雾心藤的人进去，也常有人出不来。", actions: ["hunt", "quest", "meditate"], neighbors: ["blackforge", "qingsong", "snowpeak", "songlan", "yuelu", "yunze"], resource: "雾心藤", realmId: "mist-hunt", tags: ["wild"], factionIds: ["mist-hunt-lodge"] },
  { id: "songlan", name: "松岚镇", x: 395, y: 265, region: "林麓", danger: 2, marketBias: "herb", marketTier: 0, aura: 28, terrain: "松岚坡田", desc: "镇子靠着山脚，坡上一层层都是田。天不亮就有人上山割松脂，到了晚上山风吹下来，满镇松香。", actions: ["meditate", "train", "quest"], neighbors: ["misty", "qinghe", "qingsong"], resource: "松脂草露", realmId: null, tags: ["town", "cultivation"], factionIds: ["qinghe-commons", "mist-hunt-lodge"] },
  { id: "yunling", name: "云梯岭", x: 1005, y: 265, region: "云梯", danger: 4, marketBias: "scroll", marketTier: 2, aura: 42, terrain: "云梯山道", desc: "石阶贴着山壁一路往上，走到半腰就钻进了云里。往上是玉阙，往另一头下去是边地。每年都有人在这段路上摔下去。", actions: ["train", "quest", "trade"], neighbors: ["jadegate", "redcliff", "starfall", "tianchi"], resource: "云梯符木", realmId: null, tags: ["pass", "cultivation"], factionIds: ["jadegate-courtyard", "yanpass-escort"] },
  { id: "yuelu", name: "月炉峡", x: 640, y: 280, region: "炉岭", danger: 3, marketBias: "ore", marketTier: 2, aura: 32, terrain: "炉火峡道", desc: "峡壁上凿着好些旧矿洞，洞口熏得漆黑。匠人在峡底支炉子打铁，叮叮当当的声音在两壁间来回撞。", actions: ["trade", "train", "quest"], neighbors: ["blackforge", "misty", "qingsong", "shuangqiao"], resource: "月炉矿锭", realmId: null, tags: ["forge", "wild"], factionIds: ["blackforge-guild", "mist-hunt-lodge"] },
  { id: "jadegate", name: "玉阙行院", x: 1280, y: 305, region: "行院", danger: 3, marketBias: "pill", marketTier: 3, aura: 56, terrain: "行院灵脉", desc: "玉阙在山外设的行院，白墙青瓦，门口两棵老银杏。每天一早，外院弟子在演武场上练功，喊声传到山下。", actions: ["meditate", "train", "breakthrough", "quest", "sect"], neighbors: ["danjing", "longji", "starfall", "yanpass", "yaogu", "yunling"], resource: "玉阙灵泉", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "blackforge", name: "玄铁城", x: 540, y: 340, region: "矿岭", danger: 3, marketBias: "ore", marketTier: 3, aura: 30, terrain: "火山矿脉", desc: "城里的烟囱比树还多，白天也灰蒙蒙的。满街是铁匠铺和镖局，到了夜里，巷子深处还有不挂招牌的买卖。", actions: ["trade", "train", "auction"], neighbors: ["fenglin", "misty", "qinghe", "tonglu", "yuelu"], resource: "玄铁精砂", realmId: null, tags: ["city", "market", "forge"], factionIds: ["blackforge-guild"] },
  { id: "longji", name: "龙脊道", x: 1490, y: 345, region: "龙脊", danger: 4, marketBias: "ore", marketTier: 3, aura: 34, terrain: "龙脊险道", desc: "一道石脊起起伏伏，像趴着的一条龙。南头接着边关，北头通往山门，窄的地方只容一个人侧身过去。", actions: ["train", "quest", "trade"], neighbors: ["duanyun", "huangsha", "jadegate", "songtao", "yaogu"], resource: "龙脊黑铁", realmId: null, tags: ["pass"], factionIds: ["jadegate-courtyard", "yanpass-escort"] },
  { id: "tonglu", name: "铜炉寨", x: 690, y: 370, region: "炉寨", danger: 3, marketBias: "ore", marketTier: 2, aura: 30, terrain: "铜炉寨道", desc: "寨子是围着矿坑长起来的，车道从中间穿过。打铁的、赶车的、收过路钱的，全挤在这一条街上。", actions: ["trade", "train", "quest"], neighbors: ["blackforge", "fenyuan"], resource: "铜炉矿炭", realmId: null, tags: ["forge", "pass"], factionIds: ["blackforge-guild", "yanpass-escort"] },
  { id: "redcliff", name: "赤霞崖", x: 1100, y: 370, region: "绝壁", danger: 5, marketBias: "fire", marketTier: 4, aura: 52, terrain: "丹霞绝壁", desc: "整面崖壁红得像烧过，据说是天火砸下来烫的。崖下时不时冒出异光，闯进去的人，回来的不多。", actions: ["hunt", "quest", "breakthrough"], neighbors: ["duanyun", "fenyuan", "starfall", "yanpass", "yunling"], resource: "赤焰砂", realmId: "ember-palace", tags: ["boss"], factionIds: [] },
  { id: "yunze", name: "云泽渡", x: 245, y: 395, region: "水乡", danger: 1, marketBias: "herb", marketTier: 0, aura: 26, terrain: "水泽与古渡", desc: "水网纵横，船比路多。药农在渡口卖草，行脚商在茶棚里谈价，哪边的消息都先到这儿。", actions: ["meditate", "hunt", "trade"], neighbors: ["heyuan", "hezhou", "misty", "qinghe", "reedbank", "yanzhu"], resource: "云泽灵草", realmId: "marsh-manor", tags: ["market", "starter"], factionIds: [] },
  { id: "fenyuan", name: "焚风原", x: 875, y: 410, region: "火原", danger: 4, marketBias: "fire", marketTier: 3, aura: 38, terrain: "焚风荒原", desc: "热风一年到头不停，吹得人嘴唇起皮。地上的沙是红的，有人专门来挖赤砂，一趟回来，人瘦一圈。", actions: ["hunt", "quest", "trade"], neighbors: ["redcliff", "tonglu", "wayrest"], resource: "焚原赤砂", realmId: null, tags: ["wild"], factionIds: [] },
  { id: "duanyun", name: "断云峡", x: 1310, y: 420, region: "绝峡", danger: 5, marketBias: "scroll", marketTier: 4, aura: 54, terrain: "断云裂峡", desc: "峡里的风硬得像刀，路过的云都被削成一条一条的。峡底埋着古人留下的东西，也埋着来找它们的人。", actions: ["hunt", "quest", "breakthrough"], neighbors: ["longji", "redcliff", "yanpass"], resource: "断云残经", realmId: null, tags: ["boss", "endgame"], factionIds: [] },
  { id: "yanzhu", name: "烟渚洲", x: 150, y: 430, region: "芦泽", danger: 2, marketBias: "herb", marketTier: 0, aura: 22, terrain: "烟水浅洲", desc: "洲头的雾早上压得很低。有人在芦苇里下网摸鱼，也有人蹚着水去割药苇，都得识水性。", actions: ["hunt", "quest", "meditate"], neighbors: ["hezhou", "yunze"], resource: "渚心药苇", realmId: null, tags: ["wild"], factionIds: ["mist-hunt-lodge"] },
  { id: "qinghe", name: "青禾镇", x: 435, y: 445, region: "平原", danger: 1, marketBias: "grain", marketTier: 0, aura: 20, terrain: "田镇与河道", desc: "一条河穿镇而过，两岸是稻田。镇上有药铺、铁匠铺和一间茶馆，住的多是种地的人家，偶尔也有修士路过歇脚。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "blackforge", "heyuan", "songlan", "yunze"], resource: "青禾谷露", realmId: null, tags: ["town"], factionIds: ["qinghe-commons"] },
  { id: "yanpass", name: "雁回关", x: 1180, y: 485, region: "边关", danger: 4, marketBias: "ore", marketTier: 3, aura: 22, terrain: "关城商道", desc: "关门天亮开、天黑关。镖队、运军粮的车、夹带私货的脚夫都从这一道门里过，守关的兵看人先看包袱。", actions: ["trade", "train", "quest"], neighbors: ["duanyun", "huangsha", "jadegate", "luqiao", "redcliff", "shiliangbao", "wayrest"], resource: "边关军需", realmId: null, tags: ["market", "pass"], factionIds: ["yanpass-escort"] },
  { id: "fenglin", name: "枫林镇", x: 760, y: 500, region: "林道", danger: 2, marketBias: "wood", marketTier: 1, aura: 24, terrain: "枫林驿镇", desc: "镇外是一大片枫林，秋天红得晃眼。木料、车马、脚夫都在这里换手，街上整天是吆喝声和车轱辘声。", actions: ["trade", "quest", "train"], neighbors: ["anping", "blackforge", "sangluo"], resource: "枫林车木", realmId: null, tags: ["town", "market"], factionIds: ["blackforge-guild"] },
  { id: "reedbank", name: "芦湾埠", x: 110, y: 520, region: "河港", danger: 1, marketBias: "cloth", marketTier: 1, aura: 18, terrain: "芦荡河埠", desc: "芦苇荡边上的小码头。官船、货船都在这儿靠岸，漕丁们光着膀子扛包，一扛就是一整天。", actions: ["trade", "quest", "meditate"], neighbors: ["hezhou", "yunze"], resource: "河盐布包", realmId: null, tags: ["port", "market", "court", "starter"], factionIds: ["river-transport-office"] },
  { id: "anping", name: "安平府", x: 870, y: 520, region: "州府", danger: 2, marketBias: "cloth", marketTier: 3, aura: 28, terrain: "州府街廛", desc: "州府所在，城墙高，规矩也多。办文书、缴税契、领路引，都得在衙门口排队。", actions: ["trade", "quest", "train"], neighbors: ["fenglin", "fengta", "sangluo", "wayrest"], resource: "官绢文牒", realmId: null, tags: ["city", "market", "court"], factionIds: ["anping-yamen"] },
  { id: "wayrest", name: "归帆驿", x: 1005, y: 535, region: "驿道", danger: 2, marketBias: "grain", marketTier: 1, aura: 19, terrain: "驿路集镇", desc: "东西大道上的一座驿站，驿站外头慢慢长出了一个集市。骆驼和马车在这里歇脚，粮栈的伙计整天忙着过秤。", actions: ["trade", "quest", "train"], neighbors: ["anping", "fenyuan", "hejin", "jinxi", "lantern", "shiliangbao", "yanpass"], resource: "驼铃粮栈", realmId: null, tags: ["town", "market"], factionIds: ["tide-market"] },
  { id: "lantern", name: "灯海古港", x: 1210, y: 535, region: "海港", danger: 2, marketBias: "relic", marketTier: 3, aura: 24, terrain: "海港与夜市", desc: "一到晚上，码头上的灯笼一直点到海边。远洋回来的船把稀奇古怪的货摆上夜市，讨价还价要闹到后半夜。", actions: ["trade", "auction", "quest"], neighbors: ["hejin", "wayrest", "yuhuo"], resource: "潮生珀", realmId: "tide-ruins", tags: ["city", "port", "market"], factionIds: ["tide-market"] },
  { id: "huangsha", name: "黄沙坂", x: 1440, y: 535, region: "沙坂", danger: 4, marketBias: "ore", marketTier: 2, aura: 23, terrain: "黄沙长坂", desc: "风沙把旧路桩埋了一半。熟路的镖队能认着桩子抄近道，外人走进去，常常转了一天还在原地。", actions: ["trade", "train", "quest"], neighbors: ["kuishan", "longji", "luqiao", "qionglin", "yanpass"], resource: "沙坂铁英", realmId: null, tags: ["pass", "wild"], factionIds: ["yanpass-escort"] },
  { id: "heyuan", name: "荷源镇", x: 275, y: 540, region: "水乡", danger: 1, marketBias: "herb", marketTier: 0, aura: 24, terrain: "荷塘药圃", desc: "镇子围着几口浅塘，塘里种荷，塘边种药。晴天家家院子里晒着药草，走在街上一股苦香。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "hezhou", "qinghe", "yunze"], resource: "荷塘药囊", realmId: null, tags: ["town", "starter"], factionIds: ["qinghe-commons"] },
  { id: "shiliangbao", name: "石梁堡", x: 1065, y: 540, region: "石梁", danger: 3, marketBias: "ore", marketTier: 2, aura: 24, terrain: "石梁堡道", desc: "一座石桥，一座旧堡，守着这条关道。过路的车马都要在这里歇一晚，喂马、补粮、修车轴。", actions: ["trade", "train", "quest"], neighbors: ["luqiao", "wayrest", "yanpass", "yuhuo"], resource: "石梁军粮", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort", "anping-yamen"] },
  { id: "fengta", name: "丰沓仓", x: 735, y: 600, region: "州仓", danger: 2, marketBias: "cloth", marketTier: 2, aura: 22, terrain: "官仓平码", desc: "安平府的外仓设在这里，一排排粮仓望不到头。官差拿着账册点布匹、点粮袋，数错一包要挨板子。", actions: ["trade", "quest", "train"], neighbors: ["anping", "sangluo"], resource: "丰沓布契", realmId: null, tags: ["market", "court"], factionIds: ["anping-yamen", "river-transport-office"] },
  { id: "qionglin", name: "琼林涧", x: 1540, y: 610, region: "琼林", danger: 4, marketBias: "relic", marketTier: 3, aura: 36, terrain: "琼林深涧", desc: "深涧底下有些塌了的石台，据说是古时候祭海用的。想下去捞东西的人不少，爬上来的往往少了半条命。", actions: ["hunt", "quest", "meditate"], neighbors: ["baijiao", "huangsha", "kuishan"], resource: "琼林旧祭器", realmId: null, tags: ["wild", "endgame"], factionIds: [] },
  { id: "hezhou", name: "鹤洲渡", x: 170, y: 615, region: "河泽", danger: 1, marketBias: "cloth", marketTier: 1, aura: 20, terrain: "芦荡浅渡", desc: "几条水道在这里汇成一个慢湾，水面平得像镜子。夜里也有小船悄悄靠岸，换了货就走。", actions: ["trade", "quest", "meditate"], neighbors: ["heyuan", "liuting", "reedbank", "yanzhu", "yunze"], resource: "洲心布帆", realmId: null, tags: ["port", "market"], factionIds: ["river-transport-office"] },
  { id: "baishi", name: "白石集", x: 360, y: 635, region: "石田", danger: 1, marketBias: "ore", marketTier: 1, aura: 20, terrain: "白石河集", desc: "一边是采石场，一边是粮集，满地白色的碎石子。赶集的脚商喜欢在这里凑伴拼车。", actions: ["trade", "quest", "train"], neighbors: ["heyuan", "qinghe", "taoxi"], resource: "白石砾盐", realmId: null, tags: ["town", "market"], factionIds: ["river-transport-office", "qinghe-commons"] },
  { id: "sangluo", name: "桑落镇", x: 890, y: 645, region: "桑野", danger: 1, marketBias: "cloth", marketTier: 1, aura: 21, terrain: "桑园河镇", desc: "沿河一溜都是桑园和染坊，河水一段青一段红。镇上的人说起布来，比说自家孩子还细。", actions: ["trade", "train", "quest"], neighbors: ["anping", "cangwu", "fenglin", "fengta"], resource: "桑落绢纱", realmId: null, tags: ["town", "market"], factionIds: ["anping-yamen"] },
  { id: "jinxi", name: "锦溪镇", x: 1065, y: 650, region: "水埠", danger: 1, marketBias: "cloth", marketTier: 1, aura: 20, terrain: "锦溪街市", desc: "一个靠绣活养起来的水镇，家家窗口都坐着绣娘。货郎一早收了绣片，下午就装船运走。", actions: ["trade", "quest", "train"], neighbors: ["hejin", "wayrest"], resource: "锦溪机绣", realmId: null, tags: ["town", "market"], factionIds: ["tide-market"] },
  { id: "luqiao", name: "芦桥镇", x: 1225, y: 650, region: "桥驿", danger: 2, marketBias: "grain", marketTier: 1, aura: 20, terrain: "芦桥驿镇", desc: "桥头有粮栈，有车店，去边地的人多半在这儿换车。车店老板认得每一个赶车的，也记得谁还欠着钱。", actions: ["trade", "quest", "train"], neighbors: ["guyue", "huangsha", "shiliangbao", "yanpass"], resource: "芦桥车票", realmId: null, tags: ["town", "pass"], factionIds: ["yanpass-escort"] },
  { id: "liuting", name: "柳汀村", x: 95, y: 685, region: "河湾", danger: 1, marketBias: "grain", marketTier: 0, aura: 18, terrain: "柳堤田埂", desc: "河堤外头的一个小村子，堤上一排老柳。村里人种粮、晒网，农闲时去渡口打短工。", actions: ["meditate", "train", "trade"], neighbors: ["hezhou"], resource: "柳汀新谷", realmId: null, tags: ["town", "starter"], factionIds: ["qinghe-commons"] },
  { id: "hejin", name: "鹤津镇", x: 1180, y: 690, region: "津渡", danger: 2, marketBias: "grain", marketTier: 1, aura: 21, terrain: "鹤津平码", desc: "海水和河水在这里碰头，码头上一半是海船，一半是河船。南来北往的货在这里拆了包，再换船运走。", actions: ["trade", "quest", "meditate"], neighbors: ["jinxi", "lantern", "wayrest", "yuhuo"], resource: "鹤津平码符", realmId: null, tags: ["town", "market", "port"], factionIds: ["tide-market", "river-transport-office"] },
  { id: "yuhuo", name: "渔火港", x: 1370, y: 700, region: "海口", danger: 2, marketBias: "relic", marketTier: 2, aura: 23, terrain: "渔火长汀", desc: "天一黑，滩上的渔火一盏接一盏亮起来。也有些小船不打灯，靠了岸卸下东西就走，谁也不问。", actions: ["trade", "auction", "quest"], neighbors: ["baijiao", "guyue", "hejin", "lantern", "shiliangbao"], resource: "渔火沉铜", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
  { id: "taoxi", name: "桃溪村", x: 500, y: 710, region: "平川", danger: 1, marketBias: "grain", marketTier: 0, aura: 19, terrain: "桃溪田陌", desc: "溪水绕着桃林和稻田走。春天桃花开了，过路的人都爱在这儿歇脚，喝一碗村里酿的米酒。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "cangwu"], resource: "桃溪米酿", realmId: null, tags: ["town"], factionIds: ["qinghe-commons"] },
  { id: "kuishan", name: "魁山驿", x: 1520, y: 710, region: "魁山", danger: 3, marketBias: "grain", marketTier: 2, aura: 22, terrain: "魁山驿场", desc: "往边地去，这是最后一处像样的驿站。再往前，路一天比一天难走，驿站的人见惯了去了不回的。", actions: ["trade", "train", "quest"], neighbors: ["baijiao", "huangsha", "qionglin"], resource: "魁山粮契", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort"] },
  { id: "cangwu", name: "苍坞镇", x: 760, y: 735, region: "坞野", danger: 1, marketBias: "grain", marketTier: 0, aura: 18, terrain: "坞口田庄", desc: "离官道远，消息来得慢。镇上的人守着几块粮田和鱼塘过日子，外头的事，隔一个月才传得到。", actions: ["meditate", "train", "trade"], neighbors: ["sangluo", "taoxi"], resource: "坞口陈粮", realmId: null, tags: ["town"], factionIds: ["tide-market"] },
  { id: "guyue", name: "古月滩", x: 1320, y: 760, region: "月滩", danger: 2, marketBias: "relic", marketTier: 2, aura: 24, terrain: "古月沙汀", desc: "月亮大的夜里，退了潮的沙滩上会露出一道道旧潮线。拾海的人提着灯去翻，常能翻出些老物件。", actions: ["trade", "auction", "quest"], neighbors: ["baijiao", "luqiao", "yuhuo"], resource: "古月潮砾", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
  { id: "baijiao", name: "白蛟湾", x: 1480, y: 770, region: "海湾", danger: 3, marketBias: "relic", marketTier: 2, aura: 26, terrain: "白蛟外湾", desc: "外湾的浪头又高又白，翻起来像条蛟。敢把船开出外湾的，都是奔着大买卖去的。", actions: ["trade", "quest", "hunt"], neighbors: ["guyue", "kuishan", "qionglin", "yuhuo"], resource: "白蛟海骨", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
])

export const LOCATION_MAP = new Map(LOCATIONS.map((loc) => [loc.id, loc]))

export function getLocation(locationId: string): LocationData | undefined {
  return LOCATION_MAP.get(locationId)
}
