export interface LocationData {
  id: string
  name: string
  x: number
  y: number
  region: string
  danger: number
  marketBias: string
  marketTier: number
  aura: number
  terrain: string
  desc: string
  actions: string[]
  /** 邻居地点ID */
  neighbors: string[]
  resource: string
  realmId: string | null
  tags: string[]
  /** 派系/势力ID */
  factionIds: string[]
}

function withBidirectionalNeighbors(locations: LocationData[]) {
  const neighborMap = new Map(locations.map(location => [location.id, [...location.neighbors]]))
  locations.forEach(location => {
    location.neighbors.forEach(neighborId => {
      const reverse = neighborMap.get(neighborId)
      if (reverse && !reverse.includes(location.id)) reverse.push(location.id)
    })
  })
  return locations.map(location => ({ ...location, neighbors: neighborMap.get(location.id) || [] }))
}

export const LOCATIONS: LocationData[] = withBidirectionalNeighbors([
  { id: "hemingtai", name: "鹤鸣台", x: 980, y: 80, region: "云崖", danger: 4, marketBias: "scroll", marketTier: 3, aura: 49, terrain: "鹤鸣高台", desc: "孤台常有云鹤盘旋，旁门修士在此交换残卷与讲经消息。", actions: ["meditate", "train", "quest", "sect"], neighbors: ["hanxi", "starfall", "tianchi"], resource: "鹤羽残简", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "danjing", name: "丹井坪", x: 1225, y: 80, region: "丹岭", danger: 4, marketBias: "pill", marketTier: 3, aura: 52, terrain: "丹井石坪", desc: "地火温着古井口，丹炉余温不散，是行院外炼药的暗线据点。", actions: ["meditate", "breakthrough", "quest", "sect"], neighbors: ["jadegate", "starfall", "yaogu"], resource: "丹井灵汞", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "snowpeak", name: "寒魄峰", x: 725, y: 125, region: "雪原", danger: 4, marketBias: "ice", marketTier: 3, aura: 44, terrain: "雪峰洞府", desc: "冰脉环绕的高峰，适合闭关，也容易遭遇争夺寒魄精华的强敌。", actions: ["meditate", "breakthrough", "hunt"], neighbors: ["hanxi", "misty", "qingsong", "shuangqiao"], resource: "寒魄晶", realmId: "ice-cavern", tags: ["cultivation"], factionIds: [] },
  { id: "hanxi", name: "寒溪坞", x: 850, y: 125, region: "寒溪", danger: 3, marketBias: "ice", marketTier: 2, aura: 40, terrain: "冰溪谷地", desc: "寒溪绕谷三折，适合闭气炼体，也容易撞上争泉修士。", actions: ["meditate", "breakthrough", "hunt"], neighbors: ["hemingtai", "shuangqiao", "snowpeak", "tianchi"], resource: "寒溪冰髓", realmId: null, tags: ["cultivation"], factionIds: [] },
  { id: "starfall", name: "星坠谷", x: 1115, y: 135, region: "秘境", danger: 6, marketBias: "scroll", marketTier: 5, aura: 60, terrain: "陨星裂谷", desc: "天地灵机浓郁的险地，古老残卷与异象齐现，适合寻找顶级功法。", actions: ["quest", "hunt", "breakthrough"], neighbors: ["danjing", "hemingtai", "jadegate", "redcliff", "tianchi", "yunling"], resource: "陨星残页", realmId: "star-sanctum", tags: ["boss", "endgame"], factionIds: [] },
  { id: "qingsong", name: "青松坳", x: 585, y: 155, region: "山阴", danger: 3, marketBias: "wood", marketTier: 1, aura: 34, terrain: "青松险坳", desc: "谷口尽是老松和险石，猎社常在这里截住上山下谷的路。", actions: ["hunt", "quest", "meditate"], neighbors: ["misty", "snowpeak", "songlan", "yuelu"], resource: "坳口青木", realmId: null, tags: ["wild", "cultivation"], factionIds: ["mist-hunt-lodge"] },
  { id: "yaogu", name: "药谷坪", x: 1360, y: 160, region: "药谷", danger: 3, marketBias: "herb", marketTier: 2, aura: 44, terrain: "药雾深坪", desc: "山风裹着药香，采药客和丹房行脚都把这里当中转。", actions: ["meditate", "trade", "quest"], neighbors: ["danjing", "jadegate", "longji", "songtao"], resource: "药谷灵苗", realmId: null, tags: ["cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "songtao", name: "松涛驿", x: 1560, y: 200, region: "海岬", danger: 3, marketBias: "scroll", marketTier: 2, aura: 28, terrain: "松涛岬驿", desc: "海岬旧驿被改成修士驿站，过路人多半带着见不得光的卷册。", actions: ["trade", "quest", "meditate"], neighbors: ["longji", "yaogu"], resource: "潮湿旧卷", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort"] },
  { id: "tianchi", name: "天池坪", x: 945, y: 215, region: "高岭", danger: 4, marketBias: "pill", marketTier: 3, aura: 46, terrain: "天池高坪", desc: "积雪融成的高天池泊养着灵药，清修者常在水边守夜。", actions: ["meditate", "breakthrough", "quest"], neighbors: ["hanxi", "hemingtai", "shuangqiao", "starfall", "yunling"], resource: "天池灵藻", realmId: null, tags: ["cultivation"], factionIds: [] },
  { id: "shuangqiao", name: "霜桥镇", x: 805, y: 220, region: "雪麓", danger: 2, marketBias: "ice", marketTier: 1, aura: 36, terrain: "霜桥古道", desc: "出入寒原前最后一处成形聚落，桥下寒泉终年不竭。", actions: ["meditate", "train", "trade"], neighbors: ["hanxi", "snowpeak", "tianchi", "yuelu"], resource: "霜桥泉玉", realmId: null, tags: ["town", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "misty", name: "迷雾林", x: 505, y: 255, region: "林海", danger: 2, marketBias: "wood", marketTier: 1, aura: 34, terrain: "迷雾丛林", desc: "常年雾瘴不散，潜伏着灵兽与迷失剑客，适合搜寻稀有材料。", actions: ["hunt", "quest", "meditate"], neighbors: ["blackforge", "qingsong", "snowpeak", "songlan", "yuelu", "yunze"], resource: "雾心藤", realmId: "mist-hunt", tags: ["wild"], factionIds: ["mist-hunt-lodge"] },
  { id: "songlan", name: "松岚镇", x: 395, y: 265, region: "林麓", danger: 2, marketBias: "herb", marketTier: 0, aura: 28, terrain: "松岚坡田", desc: "挨着山麓的镇子，清晨可采草，入夜还能借山风静修。", actions: ["meditate", "train", "quest"], neighbors: ["misty", "qinghe", "qingsong"], resource: "松脂草露", realmId: null, tags: ["town", "cultivation"], factionIds: ["qinghe-commons", "mist-hunt-lodge"] },
  { id: "yunling", name: "云梯岭", x: 1005, y: 265, region: "云梯", danger: 4, marketBias: "scroll", marketTier: 2, aura: 42, terrain: "云梯山道", desc: "盘山石阶像搭在云里，既通行院也通边地，是最易出岔的山路。", actions: ["train", "quest", "trade"], neighbors: ["jadegate", "redcliff", "starfall", "tianchi"], resource: "云梯符木", realmId: null, tags: ["pass", "cultivation"], factionIds: ["jadegate-courtyard", "yanpass-escort"] },
  { id: "yuelu", name: "月炉峡", x: 640, y: 280, region: "炉岭", danger: 3, marketBias: "ore", marketTier: 2, aura: 32, terrain: "炉火峡道", desc: "峡壁夹着旧炼炉与矿道，匠人和走险客都在此讨生活。", actions: ["trade", "train", "quest"], neighbors: ["blackforge", "misty", "qingsong", "shuangqiao"], resource: "月炉矿锭", realmId: null, tags: ["forge", "wild"], factionIds: ["blackforge-guild", "mist-hunt-lodge"] },
  { id: "jadegate", name: "玉阙行院", x: 1280, y: 305, region: "行院", danger: 3, marketBias: "pill", marketTier: 3, aura: 56, terrain: "行院灵脉", desc: "玉阙体系设在山外的修行行院，可以闭关突破、拜访教习，也常卷入外务与派系角力。", actions: ["meditate", "train", "breakthrough", "quest", "sect"], neighbors: ["danjing", "longji", "starfall", "yanpass", "yaogu", "yunling"], resource: "玉阙灵泉", realmId: null, tags: ["sect", "cultivation"], factionIds: ["jadegate-courtyard"] },
  { id: "blackforge", name: "玄铁城", x: 540, y: 340, region: "矿岭", danger: 3, marketBias: "ore", marketTier: 3, aura: 30, terrain: "火山矿脉", desc: "铸器师与护镖修士聚集的大城，装备交易旺盛，黑市拍卖隐于夜色。", actions: ["trade", "train", "auction"], neighbors: ["fenglin", "misty", "qinghe", "tonglu", "yuelu"], resource: "玄铁精砂", realmId: null, tags: ["city", "market", "forge"], factionIds: ["blackforge-guild"] },
  { id: "longji", name: "龙脊道", x: 1490, y: 345, region: "龙脊", danger: 4, marketBias: "ore", marketTier: 3, aura: 34, terrain: "龙脊险道", desc: "石脊一路起伏，南接边关北通山门，是高阶赶路的险道。", actions: ["train", "quest", "trade"], neighbors: ["duanyun", "huangsha", "jadegate", "songtao", "yaogu"], resource: "龙脊黑铁", realmId: null, tags: ["pass"], factionIds: ["jadegate-courtyard", "yanpass-escort"] },
  { id: "tonglu", name: "铜炉寨", x: 690, y: 370, region: "炉寨", danger: 3, marketBias: "ore", marketTier: 2, aura: 30, terrain: "铜炉寨道", desc: "矿寨与车道拧在一起，打造、押货和收保护钱的人都混在此地。", actions: ["trade", "train", "quest"], neighbors: ["blackforge", "fenyuan"], resource: "铜炉矿炭", realmId: null, tags: ["forge", "pass"], factionIds: ["blackforge-guild", "yanpass-escort"] },
  { id: "redcliff", name: "赤霞崖", x: 1100, y: 370, region: "绝壁", danger: 5, marketBias: "fire", marketTier: 4, aura: 52, terrain: "丹霞绝壁", desc: "天火曾坠之地，秘境频开，适合高风险高收益的试炼和机缘争夺。", actions: ["hunt", "quest", "breakthrough"], neighbors: ["duanyun", "fenyuan", "starfall", "yanpass", "yunling"], resource: "赤焰砂", realmId: "ember-palace", tags: ["boss"], factionIds: [] },
  { id: "yunze", name: "云泽渡", x: 245, y: 395, region: "水乡", danger: 1, marketBias: "herb", marketTier: 0, aura: 26, terrain: "水泽与古渡", desc: "水网纵横的商埠，药农、行脚商与散修在此交换第一手消息。", actions: ["meditate", "hunt", "trade"], neighbors: ["heyuan", "hezhou", "misty", "qinghe", "reedbank", "yanzhu"], resource: "云泽灵草", realmId: "marsh-manor", tags: ["market", "starter"], factionIds: [] },
  { id: "fenyuan", name: "焚风原", x: 875, y: 410, region: "火原", danger: 4, marketBias: "fire", marketTier: 3, aura: 38, terrain: "焚风荒原", desc: "热风终日不息，走货会亏体力，却能带回赤火矿砂和偏门材料。", actions: ["hunt", "quest", "trade"], neighbors: ["redcliff", "tonglu", "wayrest"], resource: "焚原赤砂", realmId: null, tags: ["wild"], factionIds: [] },
  { id: "duanyun", name: "断云峡", x: 1310, y: 420, region: "绝峡", danger: 5, marketBias: "scroll", marketTier: 4, aura: 54, terrain: "断云裂峡", desc: "峡中罡风能把云层削成碎片，古修遗物与凶险埋在同一条路上。", actions: ["hunt", "quest", "breakthrough"], neighbors: ["longji", "redcliff", "yanpass"], resource: "断云残经", realmId: null, tags: ["boss", "endgame"], factionIds: [] },
  { id: "yanzhu", name: "烟渚洲", x: 150, y: 430, region: "芦泽", danger: 2, marketBias: "herb", marketTier: 0, aura: 22, terrain: "烟水浅洲", desc: "晨雾常年压在洲头，采药和摸鱼都得看水性。", actions: ["hunt", "quest", "meditate"], neighbors: ["hezhou", "yunze"], resource: "渚心药苇", realmId: null, tags: ["wild"], factionIds: ["mist-hunt-lodge"] },
  { id: "qinghe", name: "青禾镇", x: 435, y: 445, region: "平原", danger: 1, marketBias: "grain", marketTier: 0, aura: 20, terrain: "田镇与河道", desc: "凡人与低阶修士混居的小镇，资源平稳，适合练功和补给。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "blackforge", "heyuan", "songlan", "yunze"], resource: "青禾谷露", realmId: null, tags: ["town"], factionIds: ["qinghe-commons"] },
  { id: "yanpass", name: "雁回关", x: 1180, y: 485, region: "边关", danger: 4, marketBias: "ore", marketTier: 3, aura: 22, terrain: "关城商道", desc: "关隘昼夜开阖，镖队、军需和私货都从这里过，跑商利润高，麻烦也多。", actions: ["trade", "train", "quest"], neighbors: ["duanyun", "huangsha", "jadegate", "luqiao", "redcliff", "shiliangbao", "wayrest"], resource: "边关军需", realmId: null, tags: ["market", "pass"], factionIds: ["yanpass-escort"] },
  { id: "fenglin", name: "枫林镇", x: 760, y: 500, region: "林道", danger: 2, marketBias: "wood", marketTier: 1, aura: 24, terrain: "枫林驿镇", desc: "木材、车马和脚力都在此换手，是矿岭与州府之间最忙的中继。", actions: ["trade", "quest", "train"], neighbors: ["anping", "blackforge", "sangluo"], resource: "枫林车木", realmId: null, tags: ["town", "market"], factionIds: ["blackforge-guild"] },
  { id: "reedbank", name: "芦湾埠", x: 110, y: 520, region: "河港", danger: 1, marketBias: "cloth", marketTier: 1, aura: 18, terrain: "芦荡河埠", desc: "通往州府与水乡的转运小港，官船、脚商和漕丁把南北货路系在这里。", actions: ["trade", "quest", "meditate"], neighbors: ["hezhou", "yunze"], resource: "河盐布包", realmId: null, tags: ["port", "market", "court", "starter"], factionIds: ["river-transport-office"] },
  { id: "anping", name: "安平府", x: 870, y: 520, region: "州府", danger: 2, marketBias: "cloth", marketTier: 3, aura: 28, terrain: "州府街廛", desc: "文书、税契和商旅都要在此过手，是中路最讲规矩的大城。", actions: ["trade", "quest", "train"], neighbors: ["fenglin", "fengta", "sangluo", "wayrest"], resource: "官绢文牒", realmId: null, tags: ["city", "market", "court"], factionIds: ["anping-yamen"] },
  { id: "wayrest", name: "归帆驿", x: 1005, y: 535, region: "驿道", danger: 2, marketBias: "grain", marketTier: 1, aura: 19, terrain: "驿路集镇", desc: "横贯东西的驿站集市，最适合把长线货路拆成几段慢慢滚利润。", actions: ["trade", "quest", "train"], neighbors: ["anping", "fenyuan", "hejin", "jinxi", "lantern", "shiliangbao", "yanpass"], resource: "驼铃粮栈", realmId: null, tags: ["town", "market"], factionIds: ["tide-market"] },
  { id: "lantern", name: "灯海古港", x: 1210, y: 535, region: "海港", danger: 2, marketBias: "relic", marketTier: 3, aura: 24, terrain: "海港与夜市", desc: "夜市不灭的古港大城，远航商队带来外海奇珍，也是拍卖行最活跃的地界。", actions: ["trade", "auction", "quest"], neighbors: ["hejin", "wayrest", "yuhuo"], resource: "潮生珀", realmId: "tide-ruins", tags: ["city", "port", "market"], factionIds: ["tide-market"] },
  { id: "huangsha", name: "黄沙坂", x: 1440, y: 535, region: "沙坂", danger: 4, marketBias: "ore", marketTier: 2, aura: 23, terrain: "黄沙长坂", desc: "风沙埋着旧路桩，熟路镖队能抄近，外人却常在这里失向。", actions: ["trade", "train", "quest"], neighbors: ["kuishan", "longji", "luqiao", "qionglin", "yanpass"], resource: "沙坂铁英", realmId: null, tags: ["pass", "wild"], factionIds: ["yanpass-escort"] },
  { id: "heyuan", name: "荷源镇", x: 275, y: 540, region: "水乡", danger: 1, marketBias: "herb", marketTier: 0, aura: 24, terrain: "荷塘药圃", desc: "药农围着浅塘种草晒药，是云泽外缘最稳妥的落脚点。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "hezhou", "qinghe", "yunze"], resource: "荷塘药囊", realmId: null, tags: ["town", "starter"], factionIds: ["qinghe-commons"] },
  { id: "shiliangbao", name: "石梁堡", x: 1065, y: 540, region: "石梁", danger: 3, marketBias: "ore", marketTier: 2, aura: 24, terrain: "石梁堡道", desc: "守着石桥与旧堡的关道据点，车马与押货队总要在此补给。", actions: ["trade", "train", "quest"], neighbors: ["luqiao", "wayrest", "yanpass", "yuhuo"], resource: "石梁军粮", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort", "anping-yamen"] },
  { id: "fengta", name: "丰沓仓", x: 735, y: 600, region: "州仓", danger: 2, marketBias: "cloth", marketTier: 2, aura: 22, terrain: "官仓平码", desc: "安平外仓与平码场都设在这里，税契和布匹常在此清点。", actions: ["trade", "quest", "train"], neighbors: ["anping", "sangluo"], resource: "丰沓布契", realmId: null, tags: ["market", "court"], factionIds: ["anping-yamen", "river-transport-office"] },
  { id: "qionglin", name: "琼林涧", x: 1540, y: 610, region: "琼林", danger: 4, marketBias: "relic", marketTier: 3, aura: 36, terrain: "琼林深涧", desc: "深涧里埋着旧海祭残迹，想捞宝的人常先把命搭进去半条。", actions: ["hunt", "quest", "meditate"], neighbors: ["baijiao", "huangsha", "kuishan"], resource: "琼林旧祭器", realmId: null, tags: ["wild", "endgame"], factionIds: [] },
  { id: "hezhou", name: "鹤洲渡", x: 170, y: 615, region: "河泽", danger: 1, marketBias: "cloth", marketTier: 1, aura: 20, terrain: "芦荡浅渡", desc: "几条水道在此汇成慢湾，小船夜里也敢靠岸换货。", actions: ["trade", "quest", "meditate"], neighbors: ["heyuan", "liuting", "reedbank", "yanzhu", "yunze"], resource: "洲心布帆", realmId: null, tags: ["port", "market"], factionIds: ["river-transport-office"] },
  { id: "baishi", name: "白石集", x: 360, y: 635, region: "石田", danger: 1, marketBias: "ore", marketTier: 1, aura: 20, terrain: "白石河集", desc: "小采石场和粮集混在一起，往来脚商喜欢在此拼车结伴。", actions: ["trade", "quest", "train"], neighbors: ["heyuan", "qinghe", "taoxi"], resource: "白石砾盐", realmId: null, tags: ["town", "market"], factionIds: ["river-transport-office", "qinghe-commons"] },
  { id: "sangluo", name: "桑落镇", x: 890, y: 645, region: "桑野", danger: 1, marketBias: "cloth", marketTier: 1, aura: 21, terrain: "桑园河镇", desc: "沿河一线全是桑园与染坊小作，最会把布匹攒成整批。", actions: ["trade", "train", "quest"], neighbors: ["anping", "cangwu", "fenglin", "fengta"], resource: "桑落绢纱", realmId: null, tags: ["town", "market"], factionIds: ["anping-yamen"] },
  { id: "jinxi", name: "锦溪镇", x: 1065, y: 650, region: "水埠", danger: 1, marketBias: "cloth", marketTier: 1, aura: 20, terrain: "锦溪街市", desc: "靠绢货和小手艺养起来的水镇，买卖不大却周转极快。", actions: ["trade", "quest", "train"], neighbors: ["hejin", "wayrest"], resource: "锦溪机绣", realmId: null, tags: ["town", "market"], factionIds: ["tide-market"] },
  { id: "luqiao", name: "芦桥镇", x: 1225, y: 650, region: "桥驿", danger: 2, marketBias: "grain", marketTier: 1, aura: 20, terrain: "芦桥驿镇", desc: "桥头有粮栈与车店，适合把边地货路拆成几段慢慢跑。", actions: ["trade", "quest", "train"], neighbors: ["guyue", "huangsha", "shiliangbao", "yanpass"], resource: "芦桥车票", realmId: null, tags: ["town", "pass"], factionIds: ["yanpass-escort"] },
  { id: "liuting", name: "柳汀村", x: 95, y: 685, region: "河湾", danger: 1, marketBias: "grain", marketTier: 0, aura: 18, terrain: "柳堤田埂", desc: "河堤外侧的村落，靠渡口杂役、种粮和晒网过日子。", actions: ["meditate", "train", "trade"], neighbors: ["hezhou"], resource: "柳汀新谷", realmId: null, tags: ["town", "starter"], factionIds: ["qinghe-commons"] },
  { id: "hejin", name: "鹤津镇", x: 1180, y: 690, region: "津渡", danger: 2, marketBias: "grain", marketTier: 1, aura: 21, terrain: "鹤津平码", desc: "海河相接的平码镇，南北脚商会在这里拆货转船。", actions: ["trade", "quest", "meditate"], neighbors: ["jinxi", "lantern", "wayrest", "yuhuo"], resource: "鹤津平码符", realmId: null, tags: ["town", "market", "port"], factionIds: ["tide-market", "river-transport-office"] },
  { id: "yuhuo", name: "渔火港", x: 1370, y: 700, region: "海口", danger: 2, marketBias: "relic", marketTier: 2, aura: 23, terrain: "渔火长汀", desc: "入夜后满汀火点如星，外海小货和旧器常在此悄悄上岸。", actions: ["trade", "auction", "quest"], neighbors: ["baijiao", "guyue", "hejin", "lantern", "shiliangbao"], resource: "渔火沉铜", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
  { id: "taoxi", name: "桃溪村", x: 500, y: 710, region: "平川", danger: 1, marketBias: "grain", marketTier: 0, aura: 19, terrain: "桃溪田陌", desc: "溪水绕着桃林与稻田走，凡俗人家多，修士也愿在此补给歇脚。", actions: ["meditate", "train", "trade"], neighbors: ["baishi", "cangwu"], resource: "桃溪米酿", realmId: null, tags: ["town"], factionIds: ["qinghe-commons"] },
  { id: "kuishan", name: "魁山驿", x: 1520, y: 710, region: "魁山", danger: 3, marketBias: "grain", marketTier: 2, aura: 22, terrain: "魁山驿场", desc: "边地最后一处成形驿场，过了这里再想回头就没那么容易。", actions: ["trade", "train", "quest"], neighbors: ["baijiao", "huangsha", "qionglin"], resource: "魁山粮契", realmId: null, tags: ["pass", "market"], factionIds: ["yanpass-escort"] },
  { id: "cangwu", name: "苍坞镇", x: 760, y: 735, region: "坞野", danger: 1, marketBias: "grain", marketTier: 0, aura: 18, terrain: "坞口田庄", desc: "远离官道的小镇，粮田和鱼塘比消息更靠得住。", actions: ["meditate", "train", "trade"], neighbors: ["sangluo", "taoxi"], resource: "坞口陈粮", realmId: null, tags: ["town"], factionIds: ["tide-market"] },
  { id: "guyue", name: "古月滩", x: 1320, y: 760, region: "月滩", danger: 2, marketBias: "relic", marketTier: 2, aura: 24, terrain: "古月沙汀", desc: "月夜会照出旧潮线，许多海货和古器都在退潮时显形。", actions: ["trade", "auction", "quest"], neighbors: ["baijiao", "luqiao", "yuhuo"], resource: "古月潮砾", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
  { id: "baijiao", name: "白蛟湾", x: 1480, y: 770, region: "海湾", danger: 3, marketBias: "relic", marketTier: 2, aura: 26, terrain: "白蛟外湾", desc: "外海浪急，白潮翻卷如蛟，敢出外湾的船队都图大价。", actions: ["trade", "quest", "hunt"], neighbors: ["guyue", "kuishan", "qionglin", "yuhuo"], resource: "白蛟海骨", realmId: null, tags: ["port", "market"], factionIds: ["tide-market"] },
])

export const LOCATION_MAP = new Map(LOCATIONS.map((loc) => [loc.id, loc]))

export function getLocation(locationId: string): LocationData | undefined {
  return LOCATION_MAP.get(locationId)
}
